### ISSUE TITLE
ionic angularMeteor undefined

### ISSUE THREAD

**Issue by ndevr** [Urigo/angular-meteor#123]
Hey,

after updating to v0.6.0 your urico:ionic package throw an reference error:

Uncaught ReferenceError: angularMeteor is not defined @ init.js:9

**Comment by Urigo** [comment]
@ndevr Thanks for the catch.
Fixed in https://github.com/Urigo/meteor-ionic/releases/tag/0.2.0

Please update and update me if everything works

**Comment by ndevr** [comment]
@Urigo thx, it works fine now

**Comment by Urigo** [comment]
great

**Comment by panthongw** [comment]
I am encounter this issue when I updated to the latest version. To remedy this, I added in the angular-meteor package, but the problem still persists. Could you provide a tutorial on how to pull in Angular through angular-meteor and bower. Thanks

**Comment by Urigo** [comment]
Because there isn't still an official AngularJS lib in Meteor (I'm working on it) then the best way is to use angular-meteor.

You can look at the example:  https://github.com/netanelgilad/meteor-ionic-example

but if for some reason it's not working for you please provide a repo that I can investigate
