### ISSUE TITLE
Whatsapp clone with Meteor and Angular bootstrapping not clear

### ISSUE THREAD

**Issue by ntoka** [Urigo/angular-meteor#1373]
Hey, in the Meteor Angular tutorial to produce a Whatsapp clone it is said to include ionic-scripts via Meteor npm. It is not mentioned that there are alot of warning associated with this call: 
`npm WARN peerDependencies The peer dependency angular@^1.5.3 included from ionic-scripts will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency angular-animate@^1.5.3 included from ionic-scripts will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency angular-sanitize@^1.5.3 included from ionic-scripts will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency angular-ui-router@^0.2.13 included from ionic-scripts will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly`

How do I work with this? Do I have to download those modules indiviaudally and require them somewhere?
Thanks in advance.

**Comment by pbastowski** [comment]
With npm 3 or higher ( as it says in the warning ) you will have to `npm install` each dependency individually. Then you will have to `import` each node module individually in your code before it is used.

**Comment by RylanSchaeffer** [comment]
I'm having trouble installing the last dependency. When I run "npm install angular-ui-router", I receive the following error:

npm WARN ionic-scripts@1.3.2 requires a peer of angular-ui-router@^0.2.13 but none was installed.

Do you know what the problem is?

**Comment by DAB0mB** [comment]
@ntoka Like mentioned above, install each peer dependency individually and then import them.

    $ npm install angular --save
    $ npm install angular-sanitize --save
    $ npm install angular-animate --save
    $ npm install angular-ui-router --save

@RylanSchaeffer I just released a new version of `ionic-scripts` so the problem is no longer exist.
@Urigo This issue can be closed I believe.

**Comment by Urigo** [comment]
thanks @DAB0mB 
if for someone the new tutorial is still not clear please open another issue
