### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by portah** [Urigo/angular-meteor#1755]
It is a great package I use since angular RCs. I was excited to give a try to last angular-compilers after #1599 was closed. And everything worked fine until production.  How to reproduce:

Clone boilerplate
```git clone https://github.com/Urigo/angular-meteor-base```
Add npm packages
```
    "@angular/cdk": "2.0.0-beta.12",
    "@angular/material": "2.0.0-beta.12",
    "@covalent/core": "1.0.0-beta.8-1"
```
And import
```
import {
    CovalentLayoutModule
} from '@covalent/core';
``` 
To app.modules.ts

So if I run ```meteor run``` everything works as expected, but if I do ```meteor build``` or ```meteor run --production```. I get "Unexpected token import". I just stuck, don't know where to dig further.

Thanks

**Comment by Urigo** [comment]
@portah does those same packages and dependencies work for you on a clean AngularCLI project?

**Comment by portah** [comment]
@Urigo Looks like it works. I did:

1.
```ng new atest```

2. added those 3 packages

3. in app.modules
```typescript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { ReactiveFormsModule, FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

import { AppComponent } from './app.component';

import {
    CovalentLayoutModule
} from '@covalent/core';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
         CommonModule,
        RouterModule,
        FormsModule,
        BrowserModule,
        BrowserAnimationsModule,
        ReactiveFormsModule,
        CovalentLayoutModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
4. In app.component.html, added covalent's tag <td-layout></td-layout>

5. ```ng serve``` - Browser showed the page

**Comment by Urigo** [comment]
@portah but did you try the production build?
`ng build --prod`

**Comment by portah** [comment]
@Urigo yeap, sorry didn't mention, it also works with no problem.

**Comment by leonardoespinosa** [comment]
I have the same problem when i import TranslateModule of ngx-translate in my project and run `meteor build` to create the server bundle. If i remove TranslateModule works fine. 

I created a new clean Angular CLI project as recommended by @Urigo and TranslateModule of ngx-translate works fine. My problem is reported in https://stackoverflow.com/questions/47061484/build-angular-meteor-app-fails-with-angular-compilers-0-2-5. 

I appreciate the help.

**Comment by leonardoespinosa** [comment]
I found the problem. When I import the module ngx-translate in my project, in the server bundle there is the file bundle/programs/server/packages/modules.js where it inserts the ngx-translate code in the following way:

```
import { Directive, ElementRef, Input, ChangeDetectorRef } from '@angular/core';
import { equals, isDefined } from './util';
import { TranslateService } from './translate.service';
```

The imports in `bundle/programs/server/npm/node_modules/@ngx-translate/core/src` they are in the same way.

The problem is Node doesnt support yet is6 imports ( [here you have an article that explains it](https://medium.com/the-node-js-collection/an-update-on-es6-modules-in-node-js-42c958b890c)  ) and produces the error `Uncaught SyntaxError: Unexpected token import`. 

Maybe @portah the same thing happens to you with the module `CovalentLayoutModule` (I don't know).

@Urigo How could we solve the problem?. Thanks for the help.

**Comment by ardatan** [comment]
Actually this is ngx problem, because they have to make a bundle for commonjs like other Angular libraries, but some libraries AGM, covalent, ionic doesn’t support commonjs, so we will use rollup to solve that problem.
This happens in production mode, because of AOT.
For workaround, you can disable AOT with env variable AOT=0 until the new release.

**Comment by mjwheatley** [comment]
@ardatan is this what you are suggesting?
```
export AOT=0
meteor run --production
```
I'm still getting the same error running production mode with that environment variable.

**Comment by ardatan** [comment]
Or just AOT=0 meteor run —production

**Comment by mjwheatley** [comment]
I had also tried that and it did not work either.  I also built the project, set the required environment variables and ran `node main.js`. And this also did not work.
Meteor v1.6

Do I need to try a more recent version?

**Comment by ardatan** [comment]
I see, but actually this is the problem of covalent, because they don’t have commonjs build which is only supported method by Meteor. In the next release, we’ll fix this issue by rollup bundling option(es2015 to commonjs).
Until then, you can open an issue to covalent repo for commonjs/umd problem in AOT build.
You can check this out;
https://github.com/ngx-translate/core/issues/724#issuecomment-346478005

**Comment by ardatan** [comment]
It is really hard to provide es2015 module support for Meteor, but we can mostly handle it by rollup which will be available in next release, but I strongly recommend you to keep track to the issue in ngx.

**Comment by leonardoespinosa** [comment]
@mjwheatley ngx-translate works with release [9.0.0](https://github.com/ngx-translate/core/releases/tag/v9.0.0) and the problem is solved. How @ardatan comments, the modules have to make a bundle for commonjs (isn't angular-meteor problem). But I found the same problem `Uncaught SyntaxError: Unexpected token import` with other npm modules. Some modules fix the problem with issues and others modules do nothing (unfortunately). I solved this problem with babel like this way (for the example i use ngx-page-scroll that presenting the same problem):

in your project:
1. `npm install --save babel-cli babel-preset-es2015`
2. add a npm script in package.json in "scrtipsts" scope
`"compile_ngx-page-scroll": "babel node_modules/ngx-page-scroll -d node_modules/ngx-page-scroll --presets es2015"`
3. run `npm install` to install the dependencies
4. run `npm run compile_ngx-page-scroll` and babel will compile the targeted js files
5. run your server with `meteor run --production` and should work

I hope this helps. Regards.

**Comment by ardatan** [comment]
Thank you for your cooperation. Even though the issue is not related to this package, you will be able to use `rollup` option to transpile es2015 to commonjs in next release.

**Comment by mjwheatley** [comment]
@leonardoespinosa Thanks for the write up.  I might have to give that a try.  I just tried the latest version of ngx-translate (v9.0.1), but unfortunately I am getting a different error this time and it is still not working in production mode.

**Comment by leonardoespinosa** [comment]
@mjwheatley what is the error?

**Comment by mjwheatley** [comment]
Now I am getting `ERROR TypeError: e is not a function`. I removed the `standard-minifier-js` meteor package and the error is `ERROR TypeError: factory is not a function`.
```
modules.js?hash=7de06e8ab28fbf2713cf9fea7563fabadcdf9957:formatted:24351 ERROR TypeError: factory is not a function
    at _callFactory (modules.js?hash=7de06e8ab28fbf2713cf9fea7563fabadcdf9957:formatted:34610)
    at _createProviderInstance$1 (modules.js?hash=7de06e8ab28fbf2713cf9fea7563fabadcdf9957:formatted:34556)
    at resolveNgModuleDep (modules.js?hash=7de06e8ab28fbf2713cf9fea7563fabadcdf9957:formatted:34534)
    at _createClass (modules.js?hash=7de06e8ab28fbf2713cf9fea7563fabadcdf9957:formatted:34592)
    at _createProviderInstance$1 (modules.js?hash=7de06e8ab28fbf2713cf9fea7563fabadcdf9957:formatted:34552)
    at resolveNgModuleDep (modules.js?hash=7de06e8ab28fbf2713cf9fea7563fabadcdf9957:formatted:34534)
    at NgModuleRef_.get (modules.js?hash=7de06e8ab28fbf2713cf9fea7563fabadcdf9957:formatted:35961)
    at resolveDep (modules.js?hash=7de06e8ab28fbf2713cf9fea7563fabadcdf9957:formatted:36594)
    at createClass (modules.js?hash=7de06e8ab28fbf2713cf9fea7563fabadcdf9957:formatted:36434)
    at createDirectiveInstance (modules.js?hash=7de06e8ab28fbf2713cf9fea7563fabadcdf9957:formatted:36223)
```
On this line `console.error.apply(console, values);` in the following method.
```
* @param {?} console
 * @param {...?} values
 * @return {?}
 */
                                function defaultErrorLogger(console) {
                                    var values = [];
                                    for (var _i = 1; _i < arguments.length; _i++) {
                                        values[_i - 1] = arguments[_i];
                                    }
                                    console.error.apply(console, values);
                                }
```
Any ideas?

Here are my package versions after updating:
```
"dependencies": {
    "@angular/animations": "^5.0.3",
    "@angular/common": "^5.0.3",
    "@angular/compiler": "^5.0.3",
    "@angular/core": "^5.0.3",
    "@angular/forms": "^5.0.3",
    "@angular/http": "^5.0.3",
    "@angular/platform-browser": "^5.0.3",
    "@angular/platform-browser-dynamic": "^5.0.3",
    "@angular/router": "^5.0.3",
    "@ngx-translate/core": "9.0.1",
    "@ngx-translate/http-loader": "^2.0.0",
    "babel-runtime": "^6.20.0",
    "meteor-node-stubs": "~0.3.0",
    "meteor-rxjs": "^0.4.8",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.16"
  }
```

**Comment by leonardoespinosa** [comment]
The error `ERROR TypeError: e is not a function` is not caused by ngx-translate/core, is caused by ngx-translate/http-loader. In your app.module check

`TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: (createTranslateLoader),
        deps: [HttpClient]
      }
    })`

and replace with `TranslateModule.forRoot({})` (without TranslateLoader). Run your server in production mode and should work, but your load translations from "/assets/i18n/[lang].json" not will work. Maybe you can create your own loader or create an issue in @ngx-translate/http-loader module.

**Comment by mjwheatley** [comment]
It does in fact run in production mode successfully using only `TranslateModule.forRoot()`. 

Would it help if `@ngx-translate/http-loader` was updated in the same way that that `@ngx-translate/core` was to support CommonJs?

**Comment by mjwheatley** [comment]
I changed `useFactory: (createTranslateLoader)` to `useFactory: createTranslateLoader`, removing the parenthesis around `createTranslateLoader` and it works now.

**Comment by leonardoespinosa** [comment]
Great!

**Comment by ardatan** [comment]
We've released new version of `angular-compilers` which allows you to use es6 imports in MeteorCLI by using Rollup. `ROLLUP=1`
You can check the new introduction for that.
However, we recommend to open a PR to covalent for CommonJS bundle.

**Comment by ardatan** [comment]
a

**Comment by tanybt51** [comment]
i had the same issue and the problem was in 

> angular.json

 the **popper.min.js**, i added 'umd' to the path and i got it fixed
```
 "scripts": [
              "node_modules/jquery/dist/jquery.min.js",
              "node_modules/popper.js/dist/umd/popper.min.js",
              "node_modules/bootstrap/dist/js/bootstrap.js"
            ]
```
