### ISSUE TITLE
Error when removing items from an array.

### ISSUE THREAD

**Issue by lanmower** [Urigo/angular-meteor#705]
I have tried many things today to try and work with an array of strings through angular-meteor.

This illustrates the primary thing I would expect to work:

http://meteorpad.com/pad/5r9Xz4ceRFaXfBgLb/Array-Error

If you click around the select a bit removing an item will cause a long error in the console.

I tried forcing the data in mongodb to be an array, since it more often than not, but intermittently creates an array or and object, I have tried a lot of things to get rid of this issue, even removing the array and creating a new one every time the select updates, to no avail, I still get these lengthy errors.

Is there anything I can do to work around this? am I doing it the wrong way?

**Comment by Urigo** [comment]
Fixed in `1.0.0-rc.10`

**Comment by lanmower** [comment]
I think this issue is different from #706.

It does however seem to be the same as #689

**Comment by Urigo** [comment]
Have you try to see if the pull request fixes that for you?

**Comment by lanmower** [comment]
Thanks for the response Uri.

No luck, the meteorpad seems to be fixed, however the problem is still
happening locally.

Is this possibly because meteorpad is not 1.2 yet?

**Comment by Urigo** [comment]
Hi @lanmower can you please try now with Meteor 1.2.0.2 ?
