### ISSUE TITLE
Mongo error saving subarray splice

### ISSUE THREAD

**Issue by MarkPhillips7** [Urigo/angular-meteor#793]
This issue seems very similar to https://github.com/Urigo/angular-meteor/issues/763 but might be different.

When I call save on my $meteor.object that has had a subarray spliced I get this error in the console:
> update failed: MongoError: Cannot update 'templateRelationships.14' and 'templateRelationships' at the same time

Here is what the mongo profile shows for this update attempt:
> meteor:PRIMARY> db.system.profile.find({op: {$eq:'update'}, ts: {$gt: ISODate("2015-10-28")}}).pretty()
```javascript
{
	"op" : "update",
	"ns" : "meteor.templateLibraries",
	"query" : {
		"_id" : "wHHJKRr2MhLdc4GkT"
	},
	"updateobj" : {
		"$unset" : {
			"templateRelationships.14" : true
		},
		"$pull" : {
			"templateRelationships" : null
		}
	},
	"nModified" : 0,
	"keyUpdates" : 0,
	"numYield" : 0,
	"lockStats" : {
		"timeLockedMicros" : {
			"r" : NumberLong(0),
			"w" : NumberLong(51)
		},
		"timeAcquiringMicros" : {
			"r" : NumberLong(0),
			"w" : NumberLong(3)
		}
	},
	"exception" : "Cannot update 'templateRelationships.14' and 'templateRelationships' at the same time",
	"exceptionCode" : 16837,
	"millis" : 0,
	"execStats" : {		
	},
	"ts" : ISODate("2015-10-28T12:42:39.081Z"),
	"client" : "127.0.0.1",
	"allUsers" : [ ],
	"user" : ""
}
```

**Comment by MarkPhillips7** [comment]
Here is a repo demonstrating the issue: https://github.com/MarkPhillips7/angular-meteor-issue-793

**Comment by Urigo** [comment]
Fixed in 1.0.4

**Comment by MarkPhillips7** [comment]
I have encountered this in 1.0.7. Here is mongo profiler output demonstrating the error:
```javascript
{
	"op" : "update",
	"ns" : "meteor.templateLibraries",
	"query" : {
		"_id" : "HQSXaGAuKohxZMySj"
	},
	"updateobj" : {
		"$pull" : {
			"templates.9.templateSettings" : null,
			"templates" : null
		}
	},
	"nModified" : 0,
	"keyUpdates" : 0,
	"numYield" : 0,
	"lockStats" : {
		"timeLockedMicros" : {
			"r" : NumberLong(0),
			"w" : NumberLong(116)
		},
		"timeAcquiringMicros" : {
			"r" : NumberLong(0),
			"w" : NumberLong(5)
		}
	},
	"exception" : "Cannot update 'templates.9.templateSettings' and 'templates' at the same time",
	"exceptionCode" : 16837,
	"millis" : 0,
	"execStats" : {
		
	},
	"ts" : ISODate("2015-11-08T01:04:58.776Z"),
	"client" : "127.0.0.1",
	"allUsers" : [ ],
	"user" : ""
}
```
It looks like it is not enough to issue a $pull update separate from $unset. I guess the $pull needs to be separated further if it includes a key contained within another key like how 'templates' is contained in 'templates.9.templateSettings'. So this $pull update needed to be broken into 2 $pull updates to avoid the exception.

**Comment by Urigo** [comment]
@MarkPhillips7 do you think you can make a failing test for that?
and then maybe pull request a fix???

**Comment by MarkPhillips7** [comment]
I spent some time trying to make a failing test but have been unsuccessful. Are there any test examples of capturing mongo exceptions or waiting for updates from mongo to confirm that data was not updated? I could create a test covering _updateParallel but don't know how to capture the end to end scenario.

**Comment by MarkPhillips7** [comment]
I updated https://github.com/MarkPhillips7/angular-meteor-issue-793 to demonstrate how issue still occurs.
