### ISSUE TITLE
Angular Material Styles

### ISSUE THREAD

**Issue by wickY26** [Urigo/angular-meteor#817]
When I add angular-material to my angular-meteor project everything was fine. Then I need to put md-tabs component into my project then I realized the current order of styles are not correct for my project. I run same code with the examples and yes problem is not related with angular-material.

I am new to meteor so could not find a way to solve it any suggestions?

![wrong_css](https://cloud.githubusercontent.com/assets/5011438/10890549/2eb7a952-81a1-11e5-8626-1b06bf8ec969.png)

as you see tabs label is white which is getting that style from selected tag which is wrong

![correct_css](https://cloud.githubusercontent.com/assets/5011438/10890562/4da0deb0-81a1-11e5-86dd-6bc637c99711.png)

this is the correct styles for tabs which is at the top.

the order of these styles should not be like this...

**Comment by MilosStanic** [comment]
Hi, 
I can confirm I have the same problem with active tab styling. 
I didn't have a clue it would be about order of styles. 
I can also report a problem with angular-material input box wrappers.
I have a gray artefact on md-input-container
![screenshot](http://s7.postimg.org/gl4kyp6ln/Screenshot_from_2015_11_02_17_14_36.png)

The html code is simple: 
```
<md-input-container>
	<label>Sheet Name</label>						
	<input type="text" ng-model="mc.sheet.name">
</md-input-container>
```
And the theming is also simple: 
```
$mdThemingProvider.theme('default')
    .primaryPalette('teal')
    .accentPalette('red')
    .warnPalette('orange');
```
I'm not sure how I can test if reordering styles will fix things. But this 'smells' like the same problem @wickY26 is having.

**Comment by ozsay** [comment]
There was a similar issue in angular-material that was fixed in a later version.
running 0.11.4 -> http://codepen.io/anon/pen/dYjQwx
latest version -> http://codepen.io/anon/pen/QjBJYM

It's probably it. what version on angular-material are you using?

**Comment by MilosStanic** [comment]
I'm using 0.11.4, that's the latest packed for meteor (at least it was two days ago)

**Comment by ozsay** [comment]
It's a bug that introduced in 0.11.4, so 0.11.3 is fine for that matter

**Comment by wickY26** [comment]
@ozsay @MilosStanic yes it is issue in the 0.11.4 version of angular-material we still don't have latest version at atmosphere so better to run 0.11.3 or wait for new version.

**Comment by MilosStanic** [comment]
Meanwhile I discovered that the artifact I was having with input fields was due to `md-default-theme` in one of the container divs.
